# syntax=docker/dockerfile:1

FROM quay.io/almalinux/almalinux:9

RUN rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*

RUN dnf install -y mysql-server

COPY script.sh /usr/local/sbin
RUN chmod +x /usr/local/sbin/script.sh

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
