#!/bin/bash

# Installation des paquets nécessaires
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
dnf install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
dnf install -y https://ci.tuleap.net/yum/tuleap/rhel/9/dev/x86_64/tuleap-community-release.rpm
dnf install -y \
  mysql-server \
  tuleap \
  tuleap-theme-burningparrot \
  tuleap-theme-flamingparrot \
  tuleap-plugin-tracker

# Configuration de MySQL
echo -e '[mysqld]\nsql-mode="NO_ENGINE_SUBSTITUTION"' > /etc/my.cnf.d/tuleap.cnf
systemctl enable mysqld
systemctl start mysqld

# Demande à l'utilisateur d'entrer le mot de passe MySQL
read -s -p "Entrez le mot de passe MySQL pour l'utilisateur root : " mysql_password
echo

# Demande à l'utilisateur d'entrer le nom du serveur Tuleap
read -p "Entrez le nom du serveur Tuleap : " tuleap_server_name

# Configuration de MySQL avec le mot de passe fourni par l'utilisateur
mysqladmin -u root -p"$mysql_password" password "$mysql_password"

# Configuration de Tuleap
/usr/share/tuleap/tools/setup.sh \
  --configure \
  --server-name="$tuleap_server_name" \
  --mysql-server=localhost \
  --mysql-password="$mysql_password"
